name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mq-metric:$(date +%s)
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.17.0
              
